extends Node

signal faith_changed(new_amount: float)
signal generator_changed(gen_id: int)
signal generator_cycle_complete(gen_id: int, revenue: float)
signal prophet_changed(gen_id: int)
signal prestige_done()
signal ui_needs_update()
signal toast_requested(message: String)
signal upgrade_purchased(upgrade_id: String)
signal dadiva_purchased(dadiva_id: String)
signal wisdom_changed(new_amount: int)
signal study_unlocked(study_id: String)
signal study_progress_changed(study_id: String)
signal knowledge_purchased(knowledge_id: String)
signal knowledge_activation_changed(knowledge_id: String)
signal adventure_unlocked(adventure_id: String)
signal adventure_completed(adventure_id: String)
signal relics_changed(new_amount: int)
signal gems_changed(new_amount: int)
signal boosts_changed()
signal adventure_currency_changed(currency: String, new_amount: float)
signal marco_geral_reached(adventure_id: String, quantity: int)
signal cosmetic_changed()

# Save online. O payload nunca trafega em sinais de UI: apenas hash/metadados.
signal game_state_dirty(payload_sha256: String)
signal sync_state_changed(state: String, message: String)
signal cloud_conflict_detected(summary: Dictionary)
signal cloud_identity_changed(authenticated: bool)
